apiVersion: networking.kubeslice.io/v1alpha1
kind: VpcServiceImport
metadata:
  name: cosmosdb
spec:
  sliceName: jericalla-mobile
  fqdn:
    - overflow.mongo.cosmos.azure.com # url to reach the service (can be found on the "connection strings" section)
  ports:
    - name: https
      port: 10255 # (can be found on the "connection strings" section in azure dashboard)
      protocol: HTTPS