kind: Secret
apiVersion: v1
metadata:
  name: support-api-secret
type: Opaque
data:
  # Add your secret data here, for example:
  # username: dXNlcm5hbWU= # base64 encoded value
  # password: cGFzc3dvcmQ= # base64 encoded value
  # Note: Ensure to replace the above with actual base64 encoded values of your secrets.
  # Example values:
  username: dXNlcm5hbWU= # base64 for "username"
  password: cGFzc3dvcmQ= # base64 for "password"