kind: Deployment
apiVersion: apps/v1
metadata:
  name: accounts-api
  labels:
    app: accounts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-api
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      containers:
      - name: accounts-api
        image: jgaonaakm/jericalla-mobile-api-accounts:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
  